spring:
    application:
        name: smartcontactmanager
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/scm
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        # show-sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    mail:
        host: smtp.gmail.com
        password: SECRET 
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    ssl:
                        trust: smtp.gmail.com
                    starttls:
                        enable: true
        username: ID
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-name: Google
                        client-id: ID
                        client-secret: SECRET
                        scope:
                            - email
                            - profile
                    github:
                        client-name: GitHub
                        client-id: ID
                        client-secret: SECRET
                        scope:
                            - user:email
                            - read:user
cloudinary:
    cloud.name: CLOUD_NAME
    api.key: ID
    api.secret: SECRET